# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_db
spring.datasource.username=root
spring.datasource.password=mysql3003

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Load data.sql automatically
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
